setup(name='priorityscheduler',
      version='0.1',
      description='Priority Queue to schedule custom jobs',
      url='https://github.com/TomOrth/Priority-Queue-Job-Scheduler',
      download_url='https://github.com/atf1999/executioner/tarball/0.1',
      author='Tom Orth',
      author_email='torth212@gmail.com',
      license='MIT',
      packages=['priorityscheduler'])